use_frameworks!

platform :ios, '9.0'

target 'htclinlib_Example' do
  pod 'htclinlib', :path => '../'

  target 'htclinlib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
